name: waporocw
channels:
  - defaults
dependencies:
  - gdal=2.3.*
  - matplotlib=3.3.*
  - netcdf4=1.4.*
  - notebook=6.1.*
  - numpy=1.19.*
  - pandas=1.1.*
  - pip=20.2.2=py37_0
  - pyshp=2.1.*
  - python=3.7
  - shapely=1.6.*
  - requests==2.24.*
  - pip:
    - hkvwaporpy==0.7.2


